"""Local retrieval foundations."""

from app.retrieval.lexical import (
    DuplicateChunkIdError,
    FTS5UnavailableError,
    LexicalQueryError,
    LexicalSearchResult,
    SQLiteLexicalIndex,
    is_fts5_available,
)
from app.retrieval.hybrid import (
    DEFAULT_CANDIDATE_K,
    DEFAULT_RRF_K,
    HybridProvenanceError,
    HybridRetrievalMode,
    HybridRetriever,
    HybridSearchResponse,
    HybridSearchResult,
    RetrievalSource,
    reciprocal_rank_fusion,
)
from app.retrieval.vector import (
    DEFAULT_VECTOR_COLLECTION_NAME,
    EMBEDDING_DOCUMENT_FORMAT,
    VECTOR_DISTANCE_SPACE,
    ChromaVectorIndex,
    DuplicateVectorChunkIdError,
    EmbeddingModelMismatchError,
    VectorCollectionError,
    VectorQueryError,
    VectorRetrievalError,
    VectorSearchResult,
    chunk_to_embedding_document,
)
from app.retrieval.structural import (
    STRUCTURAL_RELATION_PRIORITY,
    EvidenceOrigin,
    ExpandedCandidate,
    StructuralCause,
    StructuralExpander,
    StructuralExpansionResult,
    StructuralIndex,
    StructuralIndexError,
    StructuralLink,
    StructuralRelation,
)

__all__ = [
    "DEFAULT_CANDIDATE_K",
    "DEFAULT_RRF_K",
    "DuplicateChunkIdError",
    "DuplicateVectorChunkIdError",
    "DEFAULT_VECTOR_COLLECTION_NAME",
    "EMBEDDING_DOCUMENT_FORMAT",
    "EmbeddingModelMismatchError",
    "EvidenceOrigin",
    "ExpandedCandidate",
    "FTS5UnavailableError",
    "HybridProvenanceError",
    "HybridRetrievalMode",
    "HybridRetriever",
    "HybridSearchResponse",
    "HybridSearchResult",
    "LexicalQueryError",
    "LexicalSearchResult",
    "SQLiteLexicalIndex",
    "STRUCTURAL_RELATION_PRIORITY",
    "StructuralCause",
    "StructuralExpander",
    "StructuralExpansionResult",
    "StructuralIndex",
    "StructuralIndexError",
    "StructuralLink",
    "StructuralRelation",
    "RetrievalSource",
    "ChromaVectorIndex",
    "VECTOR_DISTANCE_SPACE",
    "VectorCollectionError",
    "VectorQueryError",
    "VectorRetrievalError",
    "VectorSearchResult",
    "chunk_to_embedding_document",
    "is_fts5_available",
    "reciprocal_rank_fusion",
]
